//
//  RandomFacts.swift
//  SportsFacts
//
//  Created by jordan kruger on 3/16/16.
//  Copyright © 2016 Treehouse. All rights reserved.
//

import Foundation
import GameKit

struct SportsFacts {
    let facts = [
        "Bo Jackson ran the fastest hand timed 40 yard dash at 4.13 seconds!",
        "Chris Johnson ran the fastest electronically timed 40 yard dash at 4.24 seconds.",
        "The Buffalo Bills made 4 consecutive super bowls and lost all 4.",
        "George Blanda played until he was 48!",
        "Justin Ernest has a NFL combine record 51 bench press reps.",
        "In 2006, LaDainian Tomlinson, running back for the San Diego Chargers, scored the most touchdowns in a single season with 31.",
        "BenJarvus Green-Ellis had 559 rushing attempts without a fumble to start his career.",
        "Matt Prater, once kicked a 64 yard field goal in a game, during the 2013 season.",
        "Drew Bledsoe, quarterback for the New England Patriots in 1994, threw 70 passes in a single game during that season!",
        "In 2007, Randy Moss, wide receiver for the New England Patriots, had the most receiving touchdowns in a single season with 23.",
        "The Chicago Bears have 741 regular season wins in their franchise history.",
        "The 2013 Denver Broncos scored 606 points during the season.",
        "In 2007, the New England Patriots scored 314 points on the road.",
        "The Tampa Bay Buccaneers only scored 20 points at home in 1977.",
        "The 2015 Pittsburgh Steelers had 8 successful two point conversions.",
        "In 1944, the Chicago Bears attempted 0 field goals all season!",
        "The Miami Dolphins allowed 4 safeties during the 2015 season.",
        "John Gagliardi has the most wins as a college football coach with 489 wins.",
        "The University of Michigan has won a total of 925 games.",
        "Travis Prentice had 862 consecutive rushes without losing a fumble, playing running back for Miami University of Ohio!",
        "Samaje Perine, running back for the University of Oklahoma, had 427 rushing yards in a single game, during the 2014 season.",
        "Barry Sanders, running back for Oklahoma State, had 37 rushing touchdowns during the 1988 season.",
        "Connor Halliday, quarterback for Washington state, had 734 passing yards in a single game in 2014 and lost the game.",
        "David Klingler once threw 11 touchdowns in a single game during the 1990 season, playing quarterback for the University of Houston.",
        "John Reaves quarterback for the University of Florida, once threw 9 interceptions in a single game.",
        "Rashaun Woods caught 7 touchdowns in one game in 2003, for Oklahoma State University!",
        "The University of Alabama is undefeated in the BCS national championship games, with 3 wins.",
        "Al Worley in 1968 and Gerod Holliman in 2014, had 14 interceptions in one season.",
        "Deltha O’Neal returned 4 interceptions for a touchdown during the 1999 season.",
        "Luke Kuechly averaged 14 tackles per game during his college career at Boston College.",
        "Terrell Suggs had 44 sacks during his college career at Arizona State.",
        "Charlie Calhoun punted 36 times in one game in 1939.",
        "Pat Brady once punted a ball, 99 yards!",
        "Antonio Perkins once scored 3 touchdowns on punt returns in one game.",
        "Ashlan Davis in 2004, scored 5 touchdowns on kickoff returns.",
        "Aroldis Chapman, who's average throw is 99 mph, once threw a baseball at 105 mph which is the fastest pitch ever recorded!",
        "The average MLB pitcher can throw 92 mph.",
        "Alex Rodriguez, has made the most money out of any baseball player during their career, making 353,416,252 dollars.",
        "The New York Yankees have made the world series 40 times and have won 27 of them.",
        "The Chicago Cubs last won the world series in 1908, which means that it’s been 107 years since they last won a world series!",
        "Yogi Berra won 10 world series championships, all with the New York Yankees.",
        "Jose Canseco once hit a home run, 540 feet.",
        "Cal Ripken Jr. played in 2,632 consecutive games, all for the Baltimore Orioles!",
        "Nolan Ryan and Cap Anson played 27 seasons. Nolan Ryan played in 1966, and from 1968 to 1993, and Cap Anson played from 1871 to 1897.",
        "Cy Young pitched 749 complete games during his career!",
        "Ty Cobb stole home base, 54 times during his career.",
        "Barry Bonds hit 762 home runs in his career.",
        "Ichiro Suzuki once had 262 hits in one season.",
        "Pete Rose had 14,053 at-bats during his career.",
        "Roy Campanella, catcher for the Brooklyn Dodgers from 1948 to 1957, had a 57.40% caught stealing rate during his career.",
        "Jamie Moyer is the oldest pitcher to win a game, he did it at the age of 49.",
        "Mike LaValliere had a 72.73% caught stealing rate during the 1993 season, playing catcher for the Chicago White Sox.",
        "Jody Davis caught 89 people stealing bases during the 1986 season, playing catcher for the Chicago Cubs",
        "Gordie Howe played in 1,767 games in 26 seasons.",
        "Henri Richard won 11 Stanley Cups, all for the Montreal Canadiens!",
        "Wayne Gretzsky scored 894 goals in his career.",
        "Jaromir Jagr has 124 career game winning goals so far in his career.",
        "Matt Martin had 382 hits during the 2014-2015 season.",
        "Roberto Luongo had 2,303 saves during the 2003-2004 season.",
        "Jonathan Toews has 40 shootout goals so far in his career, playing centre for the Chicago Blackhawks.",
        "The Montreal Canadiens have won 24 Stanley Cups!",
        "The last Canadian team to win the Stanley Cup was the Montreal Canadiens in 1993.",
        "The Toronto Maple Leafs haven’t made the Stanley Cup in 47 seasons.",
        "The 1995-1996 Detroit Red Wings had 62 regular season wins in 82 games.",
        "The 1974-1975 Washington Capitals only had 8 wins in 80 games!",
        "The 1992-1993 San Jose Sharks had 71 losses.",
        "The 1976-1977 Montreal Canadiens only had 8 losses.",
        "The Edmonton Oilers scored 446 goals during the 1983-1984 season.",
        "The Chicago Blackhawks only scored 133 goals during the 1953-1954 season.",
        "On March 24, 1936, the Detroit Red Wings and the Montreal Maroons played the longest game ever with 3 regular 20-minute periods, and 5 20-minute overtime periods, for a total of 176 minutes and 30 seconds. The final score was 1 to 0.",
        "John Wooden coached 10 out of 11 national championships won by the UCLA Bruins.",
        "In 1969-1970, Pete Maravich averaged a NCAA record 44.5 points per game, playing for the LSU Tigers!",
        "Geno Auriemma, coach for the University of Connecticut women's team, has coached 5 out of the 8 undefeated women’s basketball seasons.",
        "Geno Auriemma has also never lost in an NCAA final, with 10 wins!",
        "The University of Kentucky has a total win-loss record of 2178-673.",
        "All 14 players who have won 3 national championships, played for UCLA.",
        "Jack Taylor, a guard for Grinnell College, scored an NCAA record, 138 points in a single game during the 2012 season!",
        "Mickell Gladness, a center for Alabama A&M had 16 blocks during a game on February 24, 2007.",
        "The most 3 pointers made in a single game was 15, Keith Veney did it in 1996 for Marshall University.",
        "Basketball players used to be able to shatter backboards, and Chuck Connors was the first player to do it, on November 5, 1946!",
        "Tyler Hansbrough made 982 free throws during his career at the University of North Carolina.",
        "David Lightly played in 157 games for Ohio State during his career.",
        "Travis Bader made 504 3-pointers when he played for Oakland University from 2010 to 2014.",
        "Leroy Wright had 652 rebounds for the University of the Pacific, during the 1958-1959 season.",
        "Kenny George, who played for UNC Asheville, was the tallest college basketball player ever at 7 foot 7 inches.",
        "In 1981, the Bradley Braves and Cincinnati Bearcats played in a 7 overtime game!",
        "Sherman Douglas, Tony Fairley, and Avery Johnson, are tied for the most assists in one game, with 22.",
        "Mookie Blaylock had 13 steals twice in a game for the University of Oklahoma.",
        "Manute Bol, the tallest player in NBA history, at 7 foot 7 inches, played alongside Muggsy Bogues, the shortest player in NBA history, at 5 foot 3 inches. They played for the 1987-1988 Washington Bullets!",
        "Manute Bol had 2,086 blocked shots and scored 1,599 points during his career, which makes him the only player in NBA history, to have more blocked shots than points scored!",
        "The New York Knicks and the Boston Celtics are the only two original NBA teams that have never changed cities.",
        "The Los Angeles Clippers have never been to a conference finals in their 45 years of being a team.",
        "The Sacramento Kings haven’t been to the finals in 64 years.",
        "Robert Parish, Kevin Garnett, and Kevin Willis all played 21 seasons, during their NBA careers.",
        "The 1995-1996 Chicago Bulls have the best overall single season record of 72 wins, 10 losses",
        "The 2012 Charlotte Bobcats have the worst overall single season record of 7 wins, 59 losses.",
        "Michael Jordan played for the 1995-1996 Chicago Bulls and was the owner of the 2012 Charlotte Bobcats!",
        "The highest scoring game ever was between the Detroit Pistons and the Denver Nuggets, with a final score of 186 to 184.",
        "Oscar Robertson was the only player to average a triple double for one season, he did it for the Cincinnati Royals in 1961-1962!",
        "Dale Ellis once played 69 out of 73 minutes of a 5 overtime game on November 9, 1989, playing for the Seattle Supersonics.",
        "Wilt Chamberlain scored 100 points for the Philadelphia Warriors on March 2, 1962!",
        "Ty Lawson made 10 consecutive 3 pointers in a game on April 9, 2011.",
        "Dominique Wilkins made 23 free throws in one game with no misses on December 8, 1992, playing for the Atlanta Hawks.",
        "Dwight Howard shot 39 free throws in a game, twice, once in 2012, for the Los Angeles Lakers, and once in 2013, for the Houston Rockets.",
        "Andre Drummond missed 23 free throws in a game on January 20, 2016.",
    ]
    
    func getRandomFact() -> String {
        let randomNumber = GKRandomSource.sharedRandom().nextIntWithUpperBound(facts.count)
        
        return facts[randomNumber]
        
    }

}